# Use an existing Hasura GraphQL Engine image as the base
FROM hasura/graphql-engine:latest

# Download and install Hasura CLI
RUN curl -L https://github.com/hasura/graphql-engine/raw/master/cli/get.sh | bash

# Update Hasura CLI
RUN hasura update-cli

# Copy Hasura metadata directory from local to container
#COPY ./hasura/ /hasura/

# Set working directory to the Hasura metadata directory
WORKDIR /hasura
